import React from "react";
import { Button, Card, Layout, theme } from "antd";
import Navbar from "../components/navbar";
import DashboardUpperCards from "../components/cards/DashboardUpperCards";
import DashboardLowerCards from "../components/cards/DashboardLowerCards";
const { Content } = Layout;

const Dashboard = () => {
  const {
    token: { colorBgContainer, borderRadiusLG },
  } = theme.useToken();
  return (
      <Content
        style={{
          padding: "22px",
          height: "88vh",
        }}
      >
        <div
          style={{
            padding: 24,
            minHeight: '82vh',
            background: colorBgContainer,
            borderRadius: borderRadiusLG,
            // height: "100%",
            display: 'flex',
            gap: 20,
            flexDirection: 'column'
          }}
        >
          <DashboardUpperCards />
          <DashboardLowerCards />
            <Card type="inner" title="Download next month Estimate sales report generated by AI & ML." extra={<Button type="text">Download</Button>}>
              This generated file inclues your store's report and analysis data.
            </Card>
        </div>
      </Content>
  );
};
export default Dashboard;
